### ISSUE TITLE
 Error: Template parse errors: 'swal' is not a known element:

### ISSUE THREAD

**Issue by dyhaz** [toverux/ngx-sweetalert2#32] opened 2017-11-15 08:56 UTC
I get the following error when I try to use this library:

> Error: Uncaught (in promise): Error: Template parse errors:
'swal' is not a known element:
If 'swal' is an Angular component, then verify that it is part of this module.
To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("     <form name="form" (ngSubmit)="f.form.valid && login()" #f="ngForm" novalidate>
                [ERROR ->]<swal #dialog ></swal>
                <div class="input-group mb-3">
                  <span class=""): ng:///PagesModule/LoginComponent.html@10:16
syntaxError@webpack-internal:///../../../compiler/@angular/compiler.es5.js:1913:34
TemplateParser.prototype.parse@webpack-internal:///../../../compiler/@angular/compiler.es5.js:13010:19
JitCompiler.prototype._compileTemplate@webpack-internal:///../../../compiler/@angular/compiler.es5.js:27213:18
JitCompiler.prototype._compileComponents/<@webpack-internal:///../../../compiler/@angular/compiler.es5.js:27132:56
JitCompiler.prototype._compileComponents@webpack-internal:///../../../compiler/@angular/compiler.es5.js:27132:9
JitCompiler.prototype._compileModuleAndComponents/<@webpack-internal:///../../../compiler/@angular/compiler.es5.js:27019:13
then@webpack-internal:///../../../compiler/@angular/compiler.es5.js:1902:133
JitCompiler.prototype._compileModuleAndComponents@webpack-internal:///../../../compiler/@angular/compiler.es5.js:27018:16
JitCompiler.prototype.compileModuleAsync@webpack-internal:///../../../compiler/@angular/compiler.es5.js:26947:32
ModuleBoundCompiler.prototype.compileModuleAsync@webpack-internal:///../../../compiler/@angular/compiler.es5.js:27347:16
SystemJsNgModuleLoader.prototype.loadAndCompile/<@webpack-internal:///../../../core/@angular/core.es5.js:5862:44
ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:392:17
onInvoke@webpack-internal:///../../../core/@angular/core.es5.js:4090:24
ZoneDelegate.prototype.invoke@webpack-internal:///../../../../zone.js/dist/zone.js:391:17
Zone.prototype.run@webpack-internal:///../../../../zone.js/dist/zone.js:142:24
scheduleResolveOrReject/<@webpack-internal:///../../../../zone.js/dist/zone.js:873:52
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:425:17
onInvokeTask@webpack-internal:///../../../core/@angular/core.es5.js:4081:24
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:424:17
Zone.prototype.runTask@webpack-internal:///../../../../zone.js/dist/zone.js:192:28
drainMicroTaskQueue@webpack-internal:///../../../../zone.js/dist/zone.js:602:25
ZoneTask.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:503:21
invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:1540:9
globalZoneAwareCallback@webpack-internal:///../../../../zone.js/dist/zone.js:1566:17
Stack trace:
resolvePromise@webpack-internal:///../../../../zone.js/dist/zone.js:824:31
resolvePromise@webpack-internal:///../../../../zone.js/dist/zone.js:795:17
scheduleResolveOrReject/<@webpack-internal:///../../../../zone.js/dist/zone.js:873:17
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:425:17
onInvokeTask@webpack-internal:///../../../core/@angular/core.es5.js:4081:24
ZoneDelegate.prototype.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:424:17
Zone.prototype.runTask@webpack-internal:///../../../../zone.js/dist/zone.js:192:28
drainMicroTaskQueue@webpack-internal:///../../../../zone.js/dist/zone.js:602:25
ZoneTask.invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:503:21
invokeTask@webpack-internal:///../../../../zone.js/dist/zone.js:1540:9
globalZoneAwareCallback@webpack-internal:///../../../../zone.js/dist/zone.js:1566:17

Here is my package.json file:
> {
  "name": "`@`coreui/angular",
  "version": "1.0.5",
  "description": "Open Source Bootstrap Admin Template",
  "author": "Łukasz Holeczek",
  "homepage": "http://coreui.io",
  "copyright": "Copyright 2017 creativeLabs Łukasz Holeczek",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "`@`angular/animations": "~4.4.6",
    "`@`angular/cdk": "^5.0.0-rc0",
    "`@`angular/common": "~4.4.6",
    "`@`angular/compiler": "~4.4.6",
    "`@`angular/core": "~4.4.6",
    "`@`angular/forms": "~4.4.6",
    "`@`angular/http": "~4.4.6",
    "`@`angular/material": "^5.0.0-rc0",
    "`@`angular/platform-browser": "~4.4.6",
    "`@`angular/platform-browser-dynamic": "~4.4.6",
    "`@`angular/platform-server": "~4.4.6",
    "`@`angular/router": "~4.4.6",
    "`@`toverux/ngsweetalert2": "^2.0.1",
    "angular2-notifications": "^0.7.8",
    "bootstrap": "4.0.0-beta.2",
    "chart.js": "2.7.1",
    "core-js": "2.5.1",
    "font-awesome": "^4.7.0",
    "moment": "2.19.1",
    "ng2-charts": "1.6.0",
    "ngx-bootstrap": "1.9.3",
    "rxjs": "5.5.2",
    "simple-line-icons": "^2.4.1",
    "sweetalert2": "^6.11.5",
    "ts-helpers": "1.1.2",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "`@`angular/cli": "1.5.0",
    "`@`angular/compiler-cli": "^4.0.0",
    "`@`angular/language-service": "^4.0.0",
    "`@`types/jasmine": "~2.5.53",
    "`@`types/jasminewd2": "~2.0.2",
    "`@`types/node": "~6.0.60",
    "codelyzer": "~3.0.1",
    "jasmine-core": "2.8.0",
    "jasmine-spec-reporter": "4.2.1",
    "karma": "1.7.1",
    "karma-chrome-launcher": "2.2.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "karma-coverage-istanbul-reporter": "1.3.0",
    "protractor": "~5.1.2",
    "ts-node": "~3.0.4",
    "tslint": "~5.3.2",
    "typescript": "~2.3.3"
  },
  "engines": {
    "node": ">= 6.9.0",
    "npm": ">= 3.0.0"
  }
}

My plunk: https://plnkr.co/edit/uFUaNSvOAjwsnperAZJ5?p=preview

**Comment by toverux** [comment] 2017-11-15 09:58
The plunkr seems broken: there's a 404 when loading `app/main.ts` and the main.ts file (in src/) references an `./app.ts` file that is not listed in the Plunkr files.

Anyway, this error generally means that you didn't registered `SweetAlert2Module` properly. If you have updated the library from v.1 to v.2 without having checked for the breaking changes, please note that forRoot() is now required:

```
import { SweetAlert2Module } from '@toverux/ngsweetalert2';

@NgModule({
    //=> Basic usage
    imports: [SweetAlert2Module.forRoot()],
    
    //=> Or provide default SweetAlert2-native options
    //   (here we make Swal more Bootstrap-friendly)
    imports: [
        SweetAlert2Module.forRoot({
            buttonsStyling: false,
            customClass: 'modal-content',
            confirmButtonClass: 'btn btn-lg btn-primary',
            cancelButtonClass: 'btn btn-lg'
        })
    ],
    
    //=> In submodules only:
    imports: [SweetAlert2Module]
})
export class AppModule {
}
```

**Comment by dyhaz** [comment] 2017-11-15 11:51
@toverux 
I get this error when trying to use this library (from your example):

![image](https://user-images.githubusercontent.com/4188531/32834559-978ef1fe-ca35-11e7-9e72-f1631fa64ed9.png)

**Comment by toverux** [comment] 2017-11-15 14:38
Strange. Your setup looks good though, based on what I'm seeing.
Can you send me the content of your `package-lock.json` or `yarn.lock` ? Also, if your project does not contain sensitive, closed-source code yet, you can send me a .zip of it so I can see what's going on.

**Comment by dyhaz** [comment] 2017-11-16 03:54
@toverux Here is the link to my repository. https://github.com/dyhaz/angular4-coreui

**Comment by toverux** [comment] 2017-11-16 17:24
Hi @dyhaz, thanks for the repo!
I can't reproduce, which lets me think that something is wrong on your installation (but what, I've no idea).

It builds flawlessly with `from '@toverux/ngsweetalert2'`, as well as your `from '@toverux/ngsweetalert2/dist/esm+types/index'` workaround. I don't see what could cause such issue. Maybe just check that it's not your IDE that has a corrupted cache (sometimes they like to make us think we're wrong, while they actually are). If you don't see the same error in the console with Angular CLI, 100% it is your IDE.

I will release a new major of NgSweetAlert2 very soon. If you stil have the problem, you can eventually keep your workaround for now and wait for the new version that as a completely revised build system. If that's ok for you, I let you close the issue :)

**Comment by toverux** [comment] 2017-11-18 00:24
The new version has been release meanwhile: https://github.com/toverux/ngx-sweetalert2/releases/tag/v3.0.0
Reopen if you encounter the same problem again.

**Closed by toverux** 2017-11-18 00:25 UTC

**Comment by manuelbasanta** [comment] 2019-02-05 14:20
@dyhaz Could you solve this?
