### ISSUE TITLE
Error in angular 5

### ISSUE THREAD

**Issue by jpduranhe** [toverux/ngx-sweetalert2#35] opened 2017-11-20 14:15 UTC
hi,

I have angular 5, when install following you instructions show me this error message

ERROR in node_modules/sweetalert2/sweetalert2.d.ts(209,17): error TS2300: Duplicate identifier 'SweetAlertType'.
node_modules/sweetalert2/sweetalert2.d.ts(211,17): error TS2300: Duplicate identifier 'SweetAlertInputType'.
node_modules/sweetalert2/sweetalert2.d.ts(217,22): error TS2300: Duplicate identifier 'SweetAlertInputOptions'.
node_modules/sweetalert2/sweetalert2.d.ts(221,22): error TS2300: Duplicate identifier 'SweetAlertInputAttributes'.
node_modules/sweetalert2/sweetalert2.d.ts(678,5): error TS2300: Duplicate identifier 'default'.
src/assets/vendors/bower_components/sweetalert2/sweetalert2.d.ts(198,17): error TS2300: Duplicate identifier 'SweetAlertType'.

src/assets/vendors/bower_components/sweetalert2/sweetalert2.d.ts(200,17): error TS2300: Duplicate identifier 'SweetAlertInputType'.
src/assets/vendors/bower_components/sweetalert2/sweetalert2.d.ts(202,17): error TS2300: Duplicate identifier 'SweetAlertInputOptions'.
src/assets/vendors/bower_components/sweetalert2/sweetalert2.d.ts(204,17): error TS2300: Duplicate identifier 'SweetAlertInputAttributes'.
src/assets/vendors/bower_components/sweetalert2/sweetalert2.d.ts(232,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'html' must be of type 'string | JQ
uery', but here has type 'string'.
src/assets/vendors/bower_components/sweetalert2/sweetalert2.d.ts(402,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'preConfirm' must be of type '(inpu
tValue: any) => any', but here has type '(inputValue: any) => Promise<any>'.
src/assets/vendors/bower_components/sweetalert2/sweetalert2.d.ts(481,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'inputValidator' must be of type '(
inputValue: any) => string | Promise<string>', but here has type '(result: any) => Promise<void>'.
src/assets/vendors/bower_components/sweetalert2/sweetalert2.d.ts(493,9): error TS2403: Subsequent variable declarations must have the same type.  Variable 'progressSteps' must be of type 'st
ring[]', but here has type 'SweetAlertOptions[]'.
src/assets/vendors/bower_components/sweetalert2/sweetalert2.d.ts(520,5): error TS2300: Duplicate identifier 'default'.

thanks

**Comment by toverux** [comment] 2017-11-20 15:03
I see that you have installed SweetAlert via Bower too.
I don't know what kind of setup you have, but the problem is not coming from the library itself. You have a TypeScript error that shows that the library is installed two times (via npm _and_ via Bower).

If you don't need to install SweetAlert through Bower, just remove it from your Bower components and keep the npm version.

I'm closing the issue since I can't do anything for you here :) If you need more help, I suggest you to ask on StackOverflow, giving more infos on your project structure.

**Closed by toverux** 2017-11-20 15:03 UTC

**Comment by jpduranhe** [comment] 2017-11-20 18:29
thanks!!!!
